@endpoint = http://localhost:400/api/v1/cars

###
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
  "make": "Toyota",
  "model": "Corolla"
}

###
GET {{endpoint}} HTTP/3.0
content-type: application/json
x-api-key: blahblah

###
GET {{endpoint}}/6ab16c2ab3335595bc8ee438 HTTP/3.0
content-type: application/json

###
DELETE {{endpoint}}/6ab16c2ab3335595bc8ee438 HTTP/3.0
content-type: application/json

### update a car with lower minimum year value
PUT {{endpoint}}/6aba96a8e0a7c8fff730cf82 HTTP/3.0
content-type: application/json

{
  "make": "BMW",
  "model": "Corolla",
  "year": 1790
}

//Worksheet 4 part 2

### 
# @name postACar

POST {{endpoint}} HTTP/1.1
content-type: application/json

{
  "make": "make2",
  "model": "model2"
}

###
@newCar = {{postACar.response.body._id}}

###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json

###
GET http://localhost:400/api/v1/cars HTTP/1.1
content-type: application/json
x-api-key: blahblah

### new year field test

POST {{endpoint}} HTTP/1.1
content-type: application/json

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 2020
}

### below minimum year field test

POST {{endpoint}} HTTP/1.1
content-type: application/json

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 1940
}





### extra field error test

POST {{endpoint}} HTTP/1.1
content-type: application/json

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 2020,
  "color": "blue"
}

### missing field error test

POST {{endpoint}} HTTP/1.1
content-type: application/json

{
  "make": "Toyota"
}

### incorrect json error test

POST {{endpoint}} HTTP/1.1
content-type: application/json

{
  "make": "Toyota",
  "model": "Corolla",
}